# Use a base image with Java (e.g., OpenJDK)
FROM adoptopenjdk:11-jre-hotspot

# Set environment variables
ENV TOMCAT_VERSION 10.1.8
ENV CATALINA_HOME /opt/tomcat/
ENV PATH $CATALINA_HOME/bin:$PATH

# Install curl
RUN apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/*

# Download and install Tomcat
RUN curl -O https://archive.apache.org/dist/tomcat/tomcat-10/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz && \
    tar -xzf apache-tomcat-${TOMCAT_VERSION}.tar.gz && \
    rm apache-tomcat-${TOMCAT_VERSION}.tar.gz && \
    mv apache-tomcat-${TOMCAT_VERSION} ${CATALINA_HOME}

#Manage Jenkins and Admin credentials
RUN echo '<tomcat-users>' > /opt/tomcat/conf/tomcat-users.xml \

    && echo '  <role rolename="manager-gui"/>' >> /opt/tomcat/conf/tomcat-users.xml \

    && echo '  <role rolename="admin-gui"/>' >> /opt/tomcat/conf/tomcat-users.xml \

   && echo '<user username="admin" password="admin" roles="manager-gui"/>' >> /opt/tomcat/conf/tomcat-users.xml \

    && echo '</tomcat-users>' >> /opt/tomcat/conf/tomcat-users.xml


# Expose the default Tomcat port
EXPOSE 8080

# Launch Tomcat
CMD ["catalina.sh", "run"]
